name = "edusmart-sms"
account_id = "94cfd74b7d6b679805086b9724439a8e"
main = "backend/worker.mjs"
compatibility_date = "2026-09-26"
compatibility_flags = [
    "nodejs_compat",
    "nodejs_compat_populate_process_env",
    "enable_nodejs_http_server_modules",
    "enable_nodejs_http_modules"
]

[assets]
directory = "./frontend"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
SUPABASE_URL = "https://rhjtkuidhxwvhcirkrmm.supabase.co"
